<a href="https://colab.research.google.com/github/nnfuad/numpy0/blob/main/NumPy0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importing numpy
import numpy as np

#Array attributes

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
b = np.array([[1,2,3],
              [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [11]:
c = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]]])

d = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],

              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [12]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
c.shape,d.shape

((1, 3, 3), (2, 3, 3))

In [15]:
a.dtype,b.dtype,c.dtype,d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))

In [16]:
a.size,b.size,c.size,d.size # Determines how many elements

(3, 6, 9, 18)

In [17]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes # determines how many bites consumed

(24, 48, 72, 144)

#Array creation

In [18]:
array1 = np.array([1,2,3],dtype = int)
array1

array([1, 2, 3])

In [19]:
zeros = np.zeros((3,3), dtype =int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
ones = np.ones((3,3), dtype = int)
ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
full = np.full((3,4),5.0,dtype= float)
full

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
identity = np.identity(3,dtype = int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
eye = np.eye (3,3,)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
eye2 = np.eye(3,3,1)
eye2

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [26]:
eye3 = np.eye(3,3,-1)
eye3

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [27]:
arange = np.arange(1,10,2)
arange

array([1, 3, 5, 7, 9])

In [29]:
linspace = np.linspace(1,100,20,dtype=int)
linspace

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100])

In [30]:
linspace.size

20

In [36]:
empty = np.empty((3,1))
empty

array([[1.],
       [1.],
       [1.]])