<a href="https://colab.research.google.com/github/nnfuad/numpy0/blob/main/NumPy0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing numpy
import numpy as np

#Array attributes

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [5]:
a.ndim

1

In [7]:
b = np.array([[1,2,3],
              [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [11]:
c = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]]])

d = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],

              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [12]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
c.shape,d.shape

((1, 3, 3), (2, 3, 3))

In [15]:
a.dtype,b.dtype,c.dtype,d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))

In [16]:
a.size,b.size,c.size,d.size # Determines how many elements

(3, 6, 9, 18)

In [18]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes # determines how many bites consumed

(24, 48, 72, 144)

#Array creation

In [19]:
array1 = np.array([1,2,3],dtype = int)
array1

array([1, 2, 3])

In [21]:
zeros = np.zeros((3,3), dtype =int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
ones = np.ones((3,3), dtype = int)
ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
full = np.full((3,4),5.0,dtype= float)
full

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [27]:
identity = np.identity(3,dtype = int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
eye = np.eye()